# Generated by Django 5.0.6 on 2024-07-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='book/'),
            preserve_default=False,
        ),
    ]
