# Generated by Django 5.0.6 on 2024-07-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
